### ISSUE TITLE
how do I open the README for my current project

### ISSUE THREAD

**Issue by jmjpro** [bengreenier/vscode-node-readme#19]
The plugin works when I open a README in a node_modules module, but how do I open the my README.md for my current project?

When I provide no module name, I receive an error
```Unable to open 'Preview ''': cannot open npm-data:/. Detail: Invalid registry response.```

When I provide the name of my current module, I receive an error:
```Unable to open 'Preview 'bna-report-gen'': cannot open npm-data:/bna-report-gen. Detail: Invalid statusCode 404.```

**Comment by bengreenier** [comment]
@jmjpro do you mean you have some project like the following:

```
λ ls -al
total 20
drwxr-xr-x 1 ben 4096 0 Aug 31 11:31 .
drwxr-xr-x 1 ben 4096 0 Aug 31 11:31 ..
-rw-r--r-- 1 ben 4096 0 Aug 31 11:31 README.md
-rw-r--r-- 1 ben 4096 0 Aug 31 11:31 yourcode.js
```

and you activate the plugin with `ctrl+shift+r` or the command menu, with no `require('') or import ''` calls highlighted, receive the "Enter module name" popup, and leave it blank?

If so, I hadn't considered this a usecase for the this project, any reason you wish to do this rather than clicking the `README.md` file in the project tree and snapping the preview to the side of your editor?

**Comment by bengreenier** [comment]
closing, as I don't understand the use case. @jmjpro if you feel i'm missing something please don't hesitate to reopen! 😸
